### ISSUE TITLE
v2.3 expired

### ISSUE THREAD

**Issue by mythnc** [palmerabollo/facebook-group-crawler#3]
Graph API no longer provide access to private and closed groups :(

**Comment by palmerabollo** [comment]
Yes, I know. I don't think there is a workaround. If you know how a solution, let us know.

**Comment by mythnc** [comment]
I don't know. Maybe simulating human behavior is the only way.
Using Selenium or directly writing JavaScript could be helpful.

Ref:
https://github.com/egaoneko/fb-group-crawler
https://github.com/duongdev/vnsb-crawler
